name: linter-and-tests-check

on:
  push:
    branches: [ main ]


jobs:
  linter-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: [ '3.8', '3.9', '3.10' ]
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        make install
    - name: Analysing the code with Python linters
      run: |
        make lint
